name: fitstrike_mobile
description: FitStrike mobile app foundation.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.16.0
  flutter_map: ^6.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.3
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  latlong2: ^0.9.1
  socket_io_client: ^2.0.3+1
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - .env
